name: hooker_cooker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  dotted_border: ^3.1.0
  flutter:
    sdk: flutter
  flutter_gen: ^5.15.0
  flutter_svg: ^2.3.0
  get_storage: ^2.1.1
  liquid_glass_easy: ^4.3.1
  path: ^1.9.1
  percent_indicator: ^4.2.5
  provider: ^6.1.5+1
  sqflite: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.9 # Proyektizga mos barqaror versiyaga o'zgartirildi
  flutter_gen_runner: ^5.15.0
  flutter_launcher_icons: ^0.14.4

# Flutter Launcher Icons sozlamalari (Chap chetdan yoziladi)
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo2.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/logo2.png"
    background_color: "#ffffff" # Real hex kod yozishingiz kerak
    theme_color: "#000000"      # Real hex kod yozishingiz kerak
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/
    - assets/lotties/

  fonts:
    - family: plus
      fonts:
        - asset: assets/fonts/plus.ttf
